name: iOS Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Run iOS Tests
    runs-on: macos-14

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "16.2"

      - name: Install iOS 18.0 Simulator Runtime
        run: |
          sudo xcodebuild -downloadPlatform iOS -version 18.0 || echo "Failed to install iOS 18.0 runtime; proceeding with available runtimes"

      - name: Resolve Swift Package Dependencies
        run: xcodebuild -resolvePackageDependencies -project emoji-map.xcodeproj

      - name: Build and test
        run: |
          xcodebuild test \
            -project emoji-map.xcodeproj \
            -scheme emoji-map \
            -destination "platform=iOS Simulator,name=iPhone 16,OS=18.0" \
            -resultBundlePath TestResults.xcresult
        env:
          DEVELOPER_DIR: /Applications/Xcode_16.2.app/Contents/Developer

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always() # Upload results even if tests fail
        with:
          name: test-results
          path: TestResults.xcresult
          retention-days: 7
