name: iOS Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Run iOS Tests
    runs-on: macos-14

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "16.2"

      - name: Resolve Swift Package Dependencies
        run: xcodebuild -resolvePackageDependencies -project emoji-map.xcodeproj

      - name: Install xcpretty
        run: gem install xcpretty

      - name: Determine Simulator Destination
        id: simulator
        run: |
          echo "Listing available simulators:"
          xcrun simctl list devices available

          # Get the first available iPhone simulator
          SIMULATOR_INFO=$(xcrun simctl list devices available | grep "iPhone" | head -n 1)
          if [ -z "$SIMULATOR_INFO" ]; then
            echo "No iPhone simulators found!" >&2
            exit 1
          fi

          # Extract device name and OS version with robust parsing
          DEVICE_NAME=$(echo "$SIMULATOR_INFO" | awk '{for (i=1; i<=NF; i++) if ($i ~ /^iPhone/) {print substr($0, index($0, $i)); exit}}' | sed 's/ (.*//')
          OS_VERSION=$(echo "$SIMULATOR_INFO" | grep -oE '[0-9]+\.[0-9]+(\.[0-9]+)?' | head -n 1)

          if [ -z "$DEVICE_NAME" ] || [ -z "$OS_VERSION" ]; then
            echo "Failed to parse device name or OS version from: $SIMULATOR_INFO" >&2
            exit 1
          fi

          DESTINATION="platform=iOS Simulator,name=$DEVICE_NAME,OS=$OS_VERSION"
          echo "Selected simulator: $DESTINATION"
          echo "destination=$DESTINATION" >> $GITHUB_OUTPUT

      - name: Build and test
        run: |
          xcodebuild test \
            -project emoji-map.xcodeproj \
            -scheme emoji-map \
            -destination "${{ steps.simulator.outputs.destination }}" \
            -resultBundlePath TestResults.xcresult \
            | xcpretty
        env:
          DEVELOPER_DIR: /Applications/Xcode_16.2.app/Contents/Developer

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: TestResults.xcresult
          retention-days: 7
